### ISSUE TITLE
А не перенести ли вертикальные подписи вниз, как у горизонтальных?

### ISSUE THREAD

**Issue by Himura2la** [Himura2la/SadRobo#11]
![3kl63s5fs1m](https://cloud.githubusercontent.com/assets/7802808/16903219/7502ee94-4c80-11e6-862c-51f9e1c78afc.jpg)

**Comment by drevendev** [comment]
Чтобы у всех внизу было? Можно, только они много места от рисунков съедают.

**Comment by Himura2la** [comment]
они просто будут с другой стороны, это никак не скажется на размере рисунков. Вообще, размер ячейки под надпись щас 10% от ячейки под рисунок и вроде бы для всех рисунков норм

**Comment by Himura2la** [comment]
Fixed in 6d8a118
